apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    database: xdc
    user: xdc
    password: xdc
    url: http://influxdb:8086
    isDefault: true
    editable: true 